// <auto-generated />
using AkademikWebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AkademikWebAPI.Migrations
{
    [DbContext(typeof(AkademikDbContext))]
    partial class AkademikDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("AkademikWebAPI.Models.Akademisyen", b =>
                {
                    b.Property<int>("AkademisyenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Unvan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AkademisyenId");

                    b.ToTable("Akademisyenler");
                });

            modelBuilder.Entity("AkademikWebAPI.Models.Ders", b =>
                {
                    b.Property<string>("Kod")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AkademisyenId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Isim")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParametrelerJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Kod");

                    b.HasIndex("AkademisyenId");

                    b.ToTable("Dersler");
                });

            modelBuilder.Entity("AkademikWebAPI.Models.Ogrenci", b =>
                {
                    b.Property<string>("OgrenciNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Isim")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("OgrenciNo");

                    b.ToTable("Ogrenciler");
                });

            modelBuilder.Entity("AkademikWebAPI.Models.OgrenciDers", b =>
                {
                    b.Property<string>("OgrenciNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("DersKodu")
                        .HasColumnType("TEXT");

                    b.Property<string>("NotlarJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("OgrenciNo", "DersKodu");

                    b.HasIndex("DersKodu");

                    b.ToTable("OgrenciDersler");
                });

            modelBuilder.Entity("AkademikWebAPI.Models.Ders", b =>
                {
                    b.HasOne("AkademikWebAPI.Models.Akademisyen", "Akademisyen")
                        .WithMany("VerdigiDersler")
                        .HasForeignKey("AkademisyenId");

                    b.Navigation("Akademisyen");
                });

            modelBuilder.Entity("AkademikWebAPI.Models.OgrenciDers", b =>
                {
                    b.HasOne("AkademikWebAPI.Models.Ders", "Ders")
                        .WithMany()
                        .HasForeignKey("DersKodu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AkademikWebAPI.Models.Ogrenci", "Ogrenci")
                        .WithMany()
                        .HasForeignKey("OgrenciNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ders");

                    b.Navigation("Ogrenci");
                });

            modelBuilder.Entity("AkademikWebAPI.Models.Akademisyen", b =>
                {
                    b.Navigation("VerdigiDersler");
                });
#pragma warning restore 612, 618
        }
    }
}
